version: '3'

services:
  web:
    build: ./app/frontend
    container_name: frontend
    tty: true
    stdin_open: true
    restart: always
    command: npm run dev
    volumes:
      - ./app/frontend:/usr/app-front
    environment:
      - PORT=3000
    ports:
      - 3000:3000
    networks:
      - webchat_net

  api:
    build: ./app/backend
    container_name: backend
    tty: true
    stdin_open: true
    restart: always
    volumes:
      - ./app/backend:/usr/app-back
    environment:
      - PORT=3001
    ports:
      - 3001:3001
    networks:
      - webchat_net

networks:
  webchat_net:
    driver: bridge
